web:
  image: pandavision
  command: python -m app.runserver
  ports:
    - "8080:8080"
  links:
    - redisdb
  environment:
    - REDIS_HOST=redisdb
    - REDIS_PORT=6379

redisdb:
  image: "redis"
  ports:
    - "6379:6379"

worker:
  image: pandavision
  command: python -m app.worker
  volumes:
    - ./appdata:/data
  links:
    - redisdb
  environment:
    - REDIS_HOST=redisdb
    - REDIS_PORT=6379
    - SHARED_DATA_FOLDER=/data


